spring:
  application:
    name: wallet_service

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    producer:
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
    admin:
      auto-create: false
    bootstrap-servers: localhost:9092

server:
  port: 8010

logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG